### ISSUE TITLE
Ressource show.php will be called for /create

### ISSUE THREAD

**Issue by anken** [leocavalcante/siler#104]
Hello,
In a route resource, the path "`/create`" will also call show.php because it will match "`/{id}`".
You have to either "`exit();`" in create.php, or "`if ("create" == $params['id']) { return; }`" in show.php.
Any idea to make it work without the workarouds ?

**Comment by leocavalcante** [comment]
Well, sorry about that, it isn't indeed what you would expect, since usually frameworks implements routers+controllers and bla-bla-bla, but from Siler's nature that is the expected behavior and `exit()` or conditions are the proper solutions.

Why is that? This is how you can chain/pipe multiple behavior at you request. Siler is meant to functionally handle each HTTP request as if it is plumbing inside a Stream, so you have to explicitly close/cancel the Stream with such behavior like `exit()` or filter this "Stream" with some condition (the `if`  case).

**Comment by anken** [comment]
Hi, I agree, thanks for your answer.
