### ISSUE TITLE
Access GET/POST params in Swoole

### ISSUE THREAD

**Issue by bilabar** [leocavalcante/siler#136]
Hi Leo,

Yesterday, I tried to use Siler with Swoole. It's great. Alas, I can't access GET or POST params when I used files base route.  

index.php
```
Route\get('/3', 'controller.php', Swoole\cast($req))
```

controller.php
```
var_dump($params) // array for route [0] => 3
var_dump($req, $res) // error
var_dump(\Siler\Http\Request\get()) // null
```

Is there any way to access it?

**Comment by leocavalcante** [comment]
Hi @bilabar 
Awesome! Thanks for the interest of using Siler within Swoole!
You're right, there is no trivial way to handle Swoole's request and response objects when requiring files, that is why I changed the labels from `question` to `bug`.

To solve that, I added at `Swoole` namespace the functions: `request`, `response` and `emit`. They internally stores the current Request and Response objects and exposes getters for them.

So at `controller.php` you can:
```php
use Siler\Swoole;
$req = Swoole\request();
$req->get['param'];
```
For responses, you should favor `Swoole\emit` instead of calling the `end()` method on the Response object:
```php
Swoole\emit('Created', 201);
```

I'm working on the documentation, but you can take a look at:
https://github.com/leocavalcante/siler/tree/master/examples/swoole
To see more about that.

Hope it helps, ping me back on any issues!

PS.: use `"leocavalcante/siler": "dev-master"` while I prepare a new release.
