### ISSUE TITLE
Quick Question regarding Routes being Found

### ISSUE THREAD

**Issue by trentramseyer** [leocavalcante/siler#169]
If I use a combination of routing procedures and some of them are Resources
Is there a way to tell if a Route was successful or found?
(for ease to show 404 if not)

Example:

If i go to localhost/blog and it loads a resource file i would like to know: 

Route\get('/hello/{name}', function (array $routeParams) {
    echo 'Hello '.($routeParams['name'] ?? 'World');
});

Route\resource('/users', 'api/users');
Route\resource('/blog', 'api/blog');
Route\resource('/event', 'api/event');

if(Route\found()){
exit();
} else {
echo "404";
}

**Comment by Toastgeraet** [comment]
You can probly use 
```
Route\match(
    Route\resource('/users', 'api/users'),
    Route\resource('/blog', 'api/blog'),
    Route\resource('/event', 'api/event'),
    function () { echo "404"; } // default route if none have match.
);
```
did not test it, though...

**Comment by leocavalcante** [comment]
There is a `route_match` key on the `Container`.
You can:

```php
use Siler\Container;

if (Container\get('route_match')) {
    exit(0);
} else {
    http_response_code(404);
    echo 'Not found';
}
```

But I'll address this properly.

**Comment by leocavalcante** [comment]
There we go:
https://github.com/leocavalcante/siler/releases/tag/v1.5.2

You can keep your mindset if `did_match()` sugar:
```php
if (!Route\did_match()) {
    Response\text('Not found', 404);
}
```

https://github.com/leocavalcante/siler/blob/master/examples/route-not-found/index.php

**Comment by ha-ni-cc** [comment]
@leocavalcante Hi~
v1.5.1 upgrade to v1.5.2
Here is new something wrong when I use Siler\Swoole.
``
if (!Route\did_match()) {
        Swoole\emit('Not found', 404);
    }
``
instead of
`` 
Swoole\emit('Not found', 404);
``
When I first access it  is anything ok, but second and more times try  it was caused wrong, the request is always pending...

**Comment by leocavalcante** [comment]
Hi @ha-ni-cc 
Because of the nature of how Swoole works (it doesn't spawns a new PHP process for each request, it starts just once) you should make your files routes return a function, then Siler is able to re-compute them instead of just require it and expected something to work because it requires only once, but Siler checks if the return value of the require is a callable then stores it to call this callable on subsequent requests:
https://github.com/leocavalcante/siler/blob/master/examples/swoole/api/todos.php#L25

**Comment by ha-ni-cc** [comment]
> Hi @ha-ni-cc
> Because of the nature of how Swoole works (it doesn't spawns a new PHP process for each request, it starts just once) you should make your files routes return a function, then Siler is able to re-compute them instead of just require it and expected something to work because it requires only once, but Siler checks if the return value of the require is a callable then stores it to call this callable on subsequent requests:
> 
> 1. https://github.com/leocavalcante/siler/blob/master/examples/swoole/api/todos.php#L25
> 2. https://github.com/leocavalcante/siler/blob/master/examples/swoole/pages/home.php#L8

@leocavalcante Sorry to disturb you again！But I clone the  /example/swoole/ to test, the error still appear:
First  access is okay, second retry it return Not found for me.
I exit the running process, and restart it , first is well , second........
 Could you test it again for the example. Thanks!

**Comment by leocavalcante** [comment]
@ha-ni-cc 
You are right, sorry about that; the last update introduced a bug on Swoole environment, the `Route\DID_MATCH` wasn't being invalidated on new requests.
The v1.5.3 fixes it: https://packagist.org/packages/leocavalcante/siler#v1.5.3

**Comment by ha-ni-cc** [comment]
@leocavalcante That is all right. Siler is getting better and better.🤞
