### ISSUE TITLE
Error on DotEnv (Class 'Dotenv\Dotenv' not found)

### ISSUE THREAD

**Issue by murunwas** [leocavalcante/siler#284]
`/vlucas/phpdotenv` has changed the api from `Dotenv\Dotenv::create(__DIR__);` to `Dotenv\Dotenv::createImmutable(__DIR__);` please  update the `Siler\Dotenv\init` method.

**Comment by leocavalcante** [comment]
Hi @murunwas 
Actually, the `create` is still supported by Dotenv: https://github.com/vlucas/phpdotenv/blob/master/src/Dotenv.php#L62

You got this error because Siler adopts a peer-dependency strategy, so to use Dotenv with Siler you have to require it first, it doesn't comes with Siler out-of-the-box.

But importantly, `Dotenv` will be deprecated you the next 1.8 release and removed from 2.0, you should use `Env` instead.
