### ISSUE TITLE
When using url encoded object in query parameters the route is not recognized

### ISSUE THREAD

**Issue by gensenio** [leocavalcante/siler#354]
Im using this simple example to reproduce the issue:

```php
require_once __DIR__ . '/vendor/autoload.php';
use Siler\Functional as λ; // Just to be cool, don't use non-ASCII identifiers ;)
use Siler\Route;

Route\get('/test', λ\puts('Hello World'));
```
I serve it using php -S localhost:8888 -t .

Calling 
http://localhost:8888/test?filters%5Bstate%5D=2 
doesn't works anymore in version 1.7.3 (the route is not recognized).
It was working until version 1.7.2.

 http://localhost:8888/test?filters[state]=2 
works.

**Comment by leocavalcante** [comment]
Thank you for reporting!
Fixed at [v1.7.4](https://packagist.org/packages/leocavalcante/siler#v1.7.4)
More details at [siler-examples/issue-354](https://github.com/siler-examples/issue-354)

**Comment by gensenio** [comment]
This is the fastest bug fix i remember to date!
Thank you!

**Comment by charlyschulte** [comment]
i have the same problem, when i call a route with an url encoded javascript string (f5iOhq-XT4uibHCTuuANfC%3AAPA91bFzj682Kr_JcCiBhRHRdODtQftZnPUyntq6gf9oy1So0j5Ry4GFjwHWheJJcZynfKdDo3j4E4YXnoJMEZBif6fw5PInCzL46FGcl8EsZJgzfYJmDCIPNB8nFC5lJhVA8W73_rPY)
i didnt get a route. the problem seems to be the "%3".
would be really nice, if i could use encodeURIComponent ;)

thank you really much

**Comment by leocavalcante** [comment]
Hi @charlyschulte, can you please open a new issue sharing more details and if possible an example snippet?

**Comment by charlyschulte** [comment]
yes, no problem
