### ISSUE TITLE
Maturation

### ISSUE THREAD

**Issue by leocavalcante** [leocavalcante/siler#62]

**Comment by IvanDelsinne** [comment]
In the [Http/Response](https://github.com/leocavalcante/siler/blob/master/src/Http/Response.php#L70) file, there are a few errors in the docstrings, making it hard to debug when using IDEs with support for those docstrings.

For example, the `$content` variable should be an array, since we're JSON-Encoding it right in the call.

That could be an improvement: review and update every docstring.

**Comment by leocavalcante** [comment]
Thanks for the heads up. I'll check them out before the v1.0

**Comment by arysom** [comment]
There are few (maybe two) examples of using siler as a base framework on github, maybe there is something more out there. Adding them to the docs would help newcomers.

Also I would like to read a word in docs on using JWT lib inside Siler. This could boost interest in using Siler for rest api.

**Comment by IvanDelsinne** [comment]
I think that's a good idea.

I'm still building my personal quickstart template (including logging, jwt and such), so it may be interesting. (Hosted on my Gitlab, once it'll be "stable", I'll link it)

Besides, do you have any problem using it with JWT or is that just a general thought that some people may encounter ?

**Comment by arysom** [comment]
I will have some problems when I push my project forward :) For now I've built quick api with siler and laravel's eloquent. The next step will be authentication and authorization. I thought that it's the only thing missing in the docs. So JWT, maybe some middleware example.

**Comment by IvanDelsinne** [comment]
JWT may be too specific, but middleware could be cleared a bit, even if some issues there and there kinda guides you on how to do it. I may think about writing a bit of doc around that. But that's not really the place to talk about that, so if you want to talk about it, you can drop by by email or something like that.

**Comment by leocavalcante** [comment]
Hi @arysom, can you share your work using Siler?

**Comment by arysom** [comment]
My work is heavily based on https://github.com/manuelLandreau/siler-product and is not complete/working for now. I've tried to build tool lending library for my local community using siler(phinx for migration, eloquent for models) as a backend, similar to Manuel's work. Only difference that, I've made monolithic app using vuejs template and when it came to authorization, I've stopped, because lack of experience, and work that I've imagined - overwhelmed me a bit. So I've put the project on the shelf for now. 

I saw lcobucci/jwt inside composer and took a look inside tests, you are using helper there. I think it deserves a chapter inside the docs, similar to twig helper. It would spin the project more. If authorization, maybe also an example of middleware, the project would be feature complete.

I know that maybe you are not aiming to build a full framework. But your proposition is something different to look in php world, and having just few more things, would encourage more developers to use your work in production.
