### ISSUE TITLE
Subscription supervisor? 

### ISSUE THREAD

**Issue by clementbirkle** [leocavalcante/siler#76]
I red this  tutorial : https://siler.leocavalcante.com/graphql/subscriptions.html#starting-the-server

It sounds good but you didn't write about some possible problems with the server (exemple : after the server restart). Is it necessary to install a supervisor like http://socketo.me/docs/deploy#supervisor
And if you don't have a possibility to use a supervisor (shared hosting) , is it possible to check every time with a cron task and restart the server if necessary?

**Comment by leocavalcante** [comment]
Hi @clementbirkle 
Thanks for checking it out. I'l add a disclaimer at "Starting the server" pointing about running long-lived processes.
On shared hosting I think you must count on WHM/CPanel (and similar panels) to manage tools like Supervisord, same as you do with Cronjobs.

**Comment by clementbirkle** [comment]
Hi @leocavalcant, 

Thank you for your response. I think it could be great to add this information. 

Is it possible with a cron task to check and re-run the task like :

If (! Graphql\subscriptions($schema)->is Running()) {
    exec(php subscriptions.php);
}

**Comment by leocavalcante** [comment]
A think this closes this issue:
https://github.com/leocavalcante/siler/commit/7a3ef3f61f51fee7d2af5a1c9fb04b4df2687de1

About using cron to rerun subscriptions server, I can't add something like that because it would encourage bad practices. And about checking if it running, we cannot rely on how users would run their tasks.

In this case, you should add a pre-script that checks for a running processes before restarting it. You can check for the port, for example or PID.
